### ISSUE TITLE
vmimport role

### ISSUE THREAD

**Issue by jkongswa** [rubrikinc/use-case-aws-cloudformation-template-cloudon#17]
**What would you like to be added**:
Change the "vmimport" role to something like "rubrik-vmimport" so it's more obvious that it's an object necessary for Rubrik. Would also be good to call out the creation of this particular role in the documentation so there's awareness that it's created similar to all the other objects that are defined and subsequently created by the template.

**Why is this needed**:
Provides more clarity around what's being created, especially when it comes to troubleshooting, e.g. cleaning up a failed deployment and attempting to redeploy

**Additional context**

**Comment by drew-russell** [comment]
@jkongswa AWS requires that the role be named exactly `vmimport`. Starting with CDM v5.0 we not longer utilize the VM Import service though. @DamaniN can you confirm whether the latest changes you pushed account for this?

**Comment by DamaniN** [comment]
In CDM v5.0 we still fall back to the VMImport method if Converter does not work. The VMImport method must use a role called `vmimport`. This by design.
